# 2.2.1 Tensor

In [1]:
import torch as t
# 构建5*3矩阵，只是分配了空间，未初始化
x = t.Tensor(5, 3)
x

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [3]:
# 使用[0,1]均匀分布随机初始化二维数组
x = t.rand?

In [6]:
x = t.rand((5, 3))
x

tensor([[0.4633, 0.9819, 0.7369],
        [0.8640, 0.7132, 0.1081],
        [0.3671, 0.8531, 0.0044],
        [0.4793, 0.6788, 0.5060],
        [0.7685, 0.6693, 0.4259]])

In [10]:
print(x.size())  # torch.Size是tuple对象的子类  因此他支持tuple的所有操作

torch.Size([5, 3])


In [11]:
# 查看列的个数
x.size()[1]

3

In [12]:
x.size(1)

3

In [13]:
# 加法操作
y = t.rand(5, 3)
y

tensor([[0.9149, 0.8026, 0.0606],
        [0.3365, 0.1344, 0.0627],
        [0.0049, 0.8840, 0.8421],
        [0.9826, 0.3976, 0.8734],
        [0.7962, 0.6978, 0.0291]])

In [14]:
# 第一种写法
x + y

tensor([[1.3781, 1.7845, 0.7975],
        [1.2005, 0.8477, 0.1708],
        [0.3720, 1.7371, 0.8465],
        [1.4619, 1.0765, 1.3794],
        [1.5646, 1.3671, 0.4550]])

In [15]:
# 第二种写法
z = x.add(y)
z

tensor([[1.3781, 1.7845, 0.7975],
        [1.2005, 0.8477, 0.1708],
        [0.3720, 1.7371, 0.8465],
        [1.4619, 1.0765, 1.3794],
        [1.5646, 1.3671, 0.4550]])

In [17]:
# 第三种写法
t.add(x, y)

tensor([[1.3781, 1.7845, 0.7975],
        [1.2005, 0.8477, 0.1708],
        [0.3720, 1.7371, 0.8465],
        [1.4619, 1.0765, 1.3794],
        [1.5646, 1.3671, 0.4550]])

In [18]:
# 第四种写法
result = t.Tensor(5, 3)  # 预先分配空间
t.add(x, y, out=result)  # 输出到result

tensor([[1.3781, 1.7845, 0.7975],
        [1.2005, 0.8477, 0.1708],
        [0.3720, 1.7371, 0.8465],
        [1.4619, 1.0765, 1.3794],
        [1.5646, 1.3671, 0.4550]])

In [19]:
result

tensor([[1.3781, 1.7845, 0.7975],
        [1.2005, 0.8477, 0.1708],
        [0.3720, 1.7371, 0.8465],
        [1.4619, 1.0765, 1.3794],
        [1.5646, 1.3671, 0.4550]])

In [21]:
print(x, '\n',  y)

tensor([[0.4633, 0.9819, 0.7369],
        [0.8640, 0.7132, 0.1081],
        [0.3671, 0.8531, 0.0044],
        [0.4793, 0.6788, 0.5060],
        [0.7685, 0.6693, 0.4259]]) 
 tensor([[0.9149, 0.8026, 0.0606],
        [0.3365, 0.1344, 0.0627],
        [0.0049, 0.8840, 0.8421],
        [0.9826, 0.3976, 0.8734],
        [0.7962, 0.6978, 0.0291]])


In [27]:
# inplace加法，改变了对象的值
z = y.add_(x)
z

tensor([[2.3046, 3.7483, 2.2713],
        [2.9285, 2.2742, 0.3869],
        [1.1063, 3.4434, 0.8553],
        [2.4205, 2.4341, 2.3915],
        [3.1016, 2.7057, 1.3068]])

In [28]:
y

tensor([[2.3046, 3.7483, 2.2713],
        [2.9285, 2.2742, 0.3869],
        [1.1063, 3.4434, 0.8553],
        [2.4205, 2.4341, 2.3915],
        [3.1016, 2.7057, 1.3068]])

In [29]:
# 注意：函数名后边带下划线_的函数会修改tensor本身.而不带下划线的函数则不会修改tensor本身，带不带下划线，两种方法都会返回一个新的tensor。

In [30]:
# 选取x第一列的数据
x[:, 1]

tensor([0.9819, 0.7132, 0.8531, 0.6788, 0.6693])

In [31]:
x[..., 1]

tensor([0.9819, 0.7132, 0.8531, 0.6788, 0.6693])

In [32]:
# tensor不支持的操作可以先转成numpy然后再转回tensor
# 新建一个全是1的tensor
a = t.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [33]:
# 转成numpy
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [35]:
# numpy转tensor
import numpy as np
a = np.ones(5)
print(a)
b = t.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [36]:
# tensor和numpy共享内存所以他们之间的转换很快，而且几乎不会消耗资源，这也意味着，如果其中一个变了，另外一个也会随之改变
b.add_(1)
print(a)

[2. 2. 2. 2. 2.]


In [37]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [38]:
t.cuda.is_available()

False

In [39]:
# tensor可以通过.cuda的方法转换为GPU的tensor，从而享受GPU带来的加速运算

# 2.2.2 Autograd：自动微分

## Variable主要包含三个属性
 * data:保存Variable所包含的tensor
 * grad:保存data对应的梯度,grad也是个Variable,而不是tensor,他和data的形状一样
 * grad_fn:指向一个Function对象,这个Function用来反向传播计算输入的梯度

In [41]:
from torch.autograd import Variable

In [42]:
# 使用tensor新建一个Variable
x = Variable(t.ones(2, 2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [43]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [46]:
y = x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [47]:
y.grad

In [48]:
y.grad_fn

In [49]:
# 反向传播计算梯度
y.backward()

In [50]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [51]:
type(x.grad)

torch.Tensor

In [52]:
# grad在反向传播过程中是累加的，所以在计算反向传播前需要把梯度清零
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [55]:
# 函数以下划线结束表示inplace操作
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [56]:
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [57]:
# variable和tensor具有近乎一直的借口，在实际使用中可以无缝切换
x = Variable(t.ones(4, 5))
y = t.cos(x)
x_tensor_cos = t.cos(x.data)
print(y)
x_tensor_cos

tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])


tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])

In [58]:
type(x)

torch.Tensor